apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
spec:
  selector:
    matchLabels:
      app: webapp-mysql
  template:
    metadata:
      labels:
        app: webapp-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          # resources: 
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "webchat"
            - name: MYSQL_USER
              value: "webchat"
            - name: MYSQL_PASSWORD
              value: "webchat"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-mysql-service
spec:
  selector:
    app: mysql-webapp
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  # dependsOn:
    # - apiVersion: apps/v1 
    #   kind: Deployment
    #   name: webapp-mysql
    # - apiVersion: v1 
    #   kind: Service
    #   name: webapp-mysql-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
        prometheus.io/path: "/metrics"
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: paulopkl/imersao-gpt-webapp:latest
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            # Database Configs
            - name: DATABASE_URL
              value: "mysql://root:root@webapp-mysql-service:3306/webchat"
            - name: NEXTAUTH_URL
              value: "http://ad58cec97735a4b4b9adeada87cb2ee4-1755713443.us-east-1.elb.amazonaws.com/api/auth"
            - name: NEXTAUT_SECRET
              value: "123456"
            # Keycloak Configs
            - name: KEYCLOAK_CLIENT_ID
              value: "gpt_webapp"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "n9E5OvUhDEu1pf9csH2w86VyQjpSBqq8"
            - name: KEYCLOAK_ISSUER
              value: "http://a1aaa122782af4ffe8334502a05ea0bd-501327221.us-east-1.elb.amazonaws.com/realms/master"
            - name: CHATSERVICE_URL
              value: "chatservice-service-microsservice:50051"
