apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    # - name: metrics
    #   port: 9464
    #   protocol: TCP
    #   targetPort: 9464
