apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
spec:
  selector:
    matchLabels:
      app: webapp-mysql
  template:
    metadata:
      labels:
        app: webapp-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          # resources: 
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "webchat"
            - name: MYSQL_USER
              value: "webchat"
            - name: MYSQL_PASSWORD
              value: "webchat"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-webapp
spec:
  selector:
    app: mysql-webapp
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  dependsOn:
    # - apiVersion: apps/v1 
    #   kind: Deployment
    #   name: webapp-mysql
    - apiVersion: v1 
      kind: Service
      name: mysql-webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: paulopkl/imersao-gpt-webapp:v1
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            # Database Configs
            - name: DATABASE_URL
              value: "mysql://root:root@webapp-mysql:3306/webchat"
            - name: NEXTAUTH_URL
              value: "http://locahost:3000/api/auth"
            - name: NEXTAUT_SECRET
              value: "123456"
            # Keycloak Configs
            - name: KEYCLOAK_CLIENT_ID
              value: "gpt_webapp"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "n9E5OvUhDEu1pf9csH2w86VyQjpSBqq8"
            - name: KEYCLOAK_ISSUER
              value: "http://keycloak-service:8080/realms/master"
            - name: CHATSERVICE_URL
              value: "chatservice-service-microsservice:50051"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
