name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Command LS
      #   run: ls -la

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: true
          tags: |
            paulopkl/imersao-chatservice:v1
            paulopkl/imersao-chatservice:latest
        
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            paulopkl/imersao-gpt-webapp:v1
            paulopkl/imersao-gpt-webapp:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Authentication AWS CLI
        run: echo "Configure the AWS Configure"

      - name: Authentication AWS CLI
        run: echo "Configure the Kubectl"

      - name: Authentication AWS CLI
        run: echo "Configure the Kubectl"

      - name: Authentication AWS CLI
        run: Deploy applications

      - name: Authentication AWS CLI
        run: echo "Execute 'kubectl apply' command"
