name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Command LS
        run: ls -la
      
      - name: Docker build chatsevice
        run: echo "Docker build chatservice"
        
      - name: Docker build webapp
        run: echo "Docker build webapp"

  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authentication AWS CLI
        run: echo "Configure the AWS Configure"

      - name: Authentication AWS CLI
        run: echo "Configure the Kubectl"

      - name: Authentication AWS CLI
        run: echo "Configure the Kubectl"

      - name: Authentication AWS CLI
        run: Deploy applications

      - name: Authentication AWS CLI
        run: echo "Execute 'kubectl apply' command"
