name: CI-CD
on:
  push:
    # branches: ["main"]
    branches:
      - "*"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'
  # workflow_dispatch:
  
jobs:
  CI:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set Release Version
      #   run: |
      #     echo "BUILD_VERSION=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      # - name: Docker metadata
      #   id: metadata
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.IMG_NAME }}
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v2.2.0
        # if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
          # push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      # - name: Docker build chatservice
      #   uses: docker/build-push-action@v4.1.1
      #   with: 
      #     context: ./chatservice
      #     file: ./chatservice/Dockerfile
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_HUB_USER }}/imersao-chatservice:v${{ github.run_number }}
      #       ${{ secrets.DOCKER_HUB_USER }}/imersao-chatservice:latest
        
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/imersao-gpt-webapp:v1
            ${{ secrets.DOCKER_HUB_USER }}/imersao-gpt-webapp:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Authentication AWS CLI
        run: echo "Configure the AWS Configure"

      - name: Authentication AWS CLI
        run: echo "Configure the Kubectl"

      - name: Authentication AWS CLI
        run: echo "Configure the Kubectl"

      - name: Authentication AWS CLI
        run: Deploy applications

      - name: Authentication AWS CLI
        run: echo "Execute 'kubectl apply' command"
