name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    name: Build and push docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/imersao-chatservice:v${{ github.run_number }}
            ${{ secrets.DOCKER_HUB_USER }}/imersao-chatservice:latest
        
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/imersao-gpt-webapp:v${{ github.run_number }}
            ${{ secrets.DOCKER_HUB_USER }}/imersao-gpt-webapp:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Authentication AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ACCESS_REGION }}

      - name: Configure OpenAI API Token
        shell: bash
        run: |
          sed -i "s/{{ API_TOKEN }}/${{ secrets.OPENAI_API_KEY }}/g" ./k8s/deploy-chatservice.yaml

      - name: Configure Kubectl
        shell: bash
        run: |
          aws eks update-kubeconfig --name eks-imersao --region ${{ secrets.AWS_ACCESS_REGION }}

      - name: Apply configuration
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-chatservice.yaml
          images: |
            ${{ secrets.DOCKER_HUB_USER }}/imersao-chatservice:v${{ github.run_number }}

      # - name: Authentication AWS CLI
      #   run: echo "Execute 'kubectl apply' command"
